# Generated by Django 2.1.7 on 2019-02-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon_url', models.CharField(default='', max_length=255, null=True)),
                ('link_url', models.CharField(default='', max_length=255, null=True)),
                ('type', models.SmallIntegerField(default=1)),
                ('order', models.IntegerField(default=10000)),
                ('parent_id', models.IntegerField(default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('remark', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_sys.MenuItem')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_sys.UserGroup')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_sys.UserGroup'),
        ),
    ]
