# Generated by Django 2.1.7 on 2019-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='induction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
